services:
  network-watcher:
    image: ghrc.io/s3tupw1zard/pelican-panel-netwatch:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
        SLEEP_INTERVAL: "30" # Sleep interval in seconds